# Default values for hive-on-mr3.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: riffyninc
  name: hivemr3
  tag: 0.9.13
  pullPolicy: Always



hive:
  database:
    name: hive5mr3
    host: red0
    port: 3306
  warehouse:
    dir: /tmp/hivemr3/warehouse
  metastore:
    # if you want to create a metastore as part of this chart then change the
    # replicaCount to 1
    replicaCount: 0
    service:
      name: metastore # must be the same as metastore.host
      type: ClusterIP
    host: red0
    port: 9850
    principal: hive/red0@RED
    keytab:
      file:
    secure:
      mode: true
    heapsize: 16384
    db:
      type: MYSQL
    schema:
      verification: true
    # Moved these to values-production.yaml
    # resources:
    #   requests:
    #     cpu: 4
    #     memory: 32Gi
    #   limits:
    #     cpu: 4
    #     memory: 32Gi
    workdir:
      size: 10Gi
  server2:
    replicaCount: 1
    service:
      name: hiveserver2 # must be the same as server2.host
      type: LoadBalancer
    enable:
      doAs: false
    host: hiveserver2
    port: 9852
    principal: hive/red0@RED
    authentication:
      mode: KERBEROS
    keytab:
      file:
    heapsize: 32768
    # Moved these to values-production.yaml
    # resources:
    #   requests:
    #     cpu: 4
    #     memory: 32Gi
    #   limits:
    #     cpu: 4
    #     memory: 32Gi
    workdir:
      size: 10Gi
      nfs:
        server: "10.1.91.17"
        path: "/work/nfs/mr3-run-work-dir"
  client:
    heapsize: 32768
  mr3:
    allInOne:
      containergroup:
        memory:
          mb: 16384
        vcores: 2
    map:
      containergroup:
        memory:
          mb: 16384
        vcores: 2
    reduce:
      containergroup:
        memory:
          mb: 16384
          vcores: 2
    llap:
      headroom:
        mb: 8192

    k8s:
      pod:
        image:
          pullPolicy: Never

mr3:
  am:
    resource:
      memory:
        mb: 32768
      cpu:
        cores: 4
hadoop:
  defaultFS: file:///

  security:
    authentication:  kerberos

yarn:
  resourcemanager:
    principal: rm/red0@RED
  http:
    policy: HTTP_ONLY
  timelineService:
    hostname: indigo20
