# Default values for hive-on-mr3.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

resources:
  requests:
    cpu: 1
    memory: 4Gi
  limits:
    cpu: 2
    memory: 4Gi

mr3:
  k8s:
    pod:
      image:
        pullPolicy: Never

hive:
  warehouse:
    dir: file:///opt/mr3-run/work-dir/warehouse
  metastore:
    secure:
      mode: false
    heapsize: 2048
    dbType: mysql
  server2:
    service:
      type: NodePort
    authentication:
      mode: simple
    heapsize: 4096
  client:
    heapsize: 4096

hadoop:
  defaultFS: file:///
  security:
    authentication:  simple

workdir:
  hostPath:
     path: "/home/hivemr3/workdir"
