apiVersion: v1
kind: ReplicationController
metadata:
  namespace: {{ .Release.Namespace }}
  name: hivemr3-hiveserver2
spec:
  replicas: {{ .Values.hive.server2.replicaCount}}
  selector:
    hivemr3_hive_source: hivesrc5
    hivemr3_app: hiveserver2
  template:
    metadata:
      namespace: {{ .Release.Namespace }}
      name: hivemr3-hiveserver2
      labels:
        hivemr3_hive_source: hivesrc5
        hivemr3_app: hiveserver2
        mr3-pod-role: master-role
    spec:
      serviceAccountName: hive-service-account
      restartPolicy: Always
      hostAliases:
      - ip: "10.1.90.9"
        hostnames:
        - "gold0"
      - ip: "10.1.91.4"
        hostnames:
        - "red0"
      - ip: "10.1.91.41"
        hostnames:
        - "indigo20"
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  hivemr3_app: metastore
      containers:
      - image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
        command: ["/opt/mr3-run/hive/hiveserver2-service.sh"]
        args: ["start", "--kubernetes"]
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: hiveserver2
        env:
        - name: CLIENT_TO_AM_TOKEN_KEY
          valueFrom:
            configMapKeyRef:
              name: client-am-config
              key: key
        - name: MR3_APPLICATION_ID_TIMESTAMP
          valueFrom:
            configMapKeyRef:
              name: client-am-config
              key: timestamp
        - name: MR3_SHARED_SESSION_ID
          valueFrom:
            configMapKeyRef:
              name: client-am-config
              key: mr3sessionid
        - name: ATS_SECRET_KEY
          valueFrom:
            configMapKeyRef:
              name: client-am-config
              key: ats-secret-key
        {{ if .Values.hive.server2.resources}}
        resources:
          requests:
            cpu: {{ .Values.hive.server2.resources.requests.cpu}}
            memory: {{ .Values.hive.server2.resources.requests.memory}}
          limits:
            cpu: {{ .Values.hive.server2.resources.limits.cpu}}
            memory: {{ .Values.hive.server2.resources.limits.memory}}
        {{ end }}
        ports:
        - containerPort: 9852
          protocol: TCP
        volumeMounts:
        - name: env-k8s-volume
          mountPath: /opt/mr3-run/env.sh
          subPath: env.sh
        - name: conf-k8s-volume
          mountPath: /opt/mr3-run/conf/
          readOnly: true
        - name: key-k8s-volume
          mountPath: /opt/mr3-run/key/
          readOnly: true
        - name: am-local-k8s-volume
          mountPath: /opt/mr3-run/am-local-dir
        - name: work-dir-volume
          mountPath: /opt/mr3-run/work-dir
        - name: hiveserver2-ranger-policy-k8s-volume
          mountPath: /opt/mr3-run/hiveserver2-ranger-policycache
      volumes:
      - name: env-k8s-volume
        configMap:
          name: env-configmap
      - name: conf-k8s-volume
        configMap:
          name: hivemr3-conf-configmap
      - name: key-k8s-volume
        secret:
          secretName: hivemr3-keytab-secret
      - name: am-local-k8s-volume
        emptyDir: {}
      - name: work-dir-volume
        persistentVolumeClaim:
          claimName: workdir-pvc
      - name: hiveserver2-ranger-policy-k8s-volume
        emptyDir: {}
