apiVersion: v1
kind: PersistentVolume
metadata:
  name: hiveserver2-workdir-pv
spec:
  capacity:
    storage: {{ .Values.hive.server2.workdir.size }}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  {{if .Values.hive.server2.workdir.hostPath }}
  hostPath:
    path: {{ .Values.hive.server2.workdir.hostPath.path }}
  {{else if .Values.workdir.nfs }}
  nfs:
    server: {{ .Values.workdir.nfs.server }}
    path: {{ .Values.workdir.nfs.path }}
  {{ else }}
  nfs:
    server: "10.1.91.17"
    path: "/work/nfs/mr3-run-work-dir"
  {{ end }}
