apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hive-role-binding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: hive-role
subjects:
- kind: ServiceAccount
  name: hive-service-account
  namespace: {{ .Release.Namespace }}
