{{ if gt .Values.hive.metastore.replicaCount 0.0 }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: {{ .Release.Namespace }}
  name: hivemr3-metastore
spec:
  serviceName: metastore
  replicas: {{ .Values.hive.metastore.replicaCount}}
  selector:
    matchLabels:
      hivemr3_hive_source: hivesrc5
      hivemr3_app: metastore
  template:
    metadata:
      namespace: {{ .Release.Namespace }}
      name: hivemr3-metastore
      labels:
        hivemr3_hive_source: hivesrc5
        hivemr3_app: metastore
        mr3-pod-role: master-role
    spec:
      serviceAccountName: metastore-service-account
      restartPolicy: Always
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  hivemr3_app: ranger
      hostAliases:
      - ip: "10.1.90.9"
        hostnames:
        - "gold0"
      - ip: "10.1.91.4"
        hostnames:
        - "red0"
      - ip: "10.1.91.17"
        hostnames:
        - "indigo0"
      containers:
      - image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
        command: ["/opt/mr3-run/hive/metastore-service.sh"]
        args: ["start", "--init-schema"]
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: metastore
        {{ if .Values.hive.metastore.resources}}
        resources:
          requests:
            cpu: {{ .Values.hive.metastore.resources.requests.cpu}}
            memory: {{ .Values.hive.metastore.resources.requests.memory}}
          limits:
            cpu: {{ .Values.hive.metastore.resources.limits.cpu}}
            memory: {{ .Values.hive.metastore.resources.limits.memory}}
        {{ end }}
        ports:
        - containerPort: {{ .Values.hive.metastore.port }}
          protocol: TCP
        volumeMounts:
        - name: env-k8s-volume
          mountPath: /opt/mr3-run/env.sh
          subPath: env.sh
        - name: conf-k8s-volume
          mountPath: /opt/mr3-run/conf/
          readOnly: true
        - name: key-k8s-volume
          mountPath: /opt/mr3-run/key/
          readOnly: true
      volumes:
      - name: env-k8s-volume
        configMap:
          name: env-configmap
      - name: conf-k8s-volume
        configMap:
          name: hivemr3-conf-configmap
      - name: key-k8s-volume
        secret:
          secretName: hivemr3-keytab-secret
{{ end }}
