{{ if gt .Values.hive.metastore.replicaCount 0.0 }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Release.Namespace }}
  name: metastore-workdir-pvc
spec:
  resources:
    requests:
      storage: {{ .Values.hive.metastore.workdir.size }}
  accessModes:
  - ReadWriteMany
  storageClassName: ""
{{ end }}
